<?xml version="1.0" encoding="utf-8"?><Database Name="EVMD" Class="dbmlLoginDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OJN7U69;Initial Catalog=EVMD;Integrated Security=True" SettingsObjectName="Phan_mem_Tu_dien_ho_tro_mon_Toan_Tieng_Anh_THPT___EVMD.Properties.Settings" SettingsPropertyName="EVMDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Permission" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>