#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan_mem_Tu_dien_ho_tro_mon_Toan_Tieng_Anh_THPT___EVMD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EVMD")]
	public partial class dbmlDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertData(Data instance);
    partial void UpdateData(Data instance);
    partial void DeleteData(Data instance);
    partial void InsertGrade(Grade instance);
    partial void UpdateGrade(Grade instance);
    partial void DeleteGrade(Grade instance);
    #endregion
		
		public dbmlDataDataContext() : 
				base(global::Phan_mem_Tu_dien_ho_tro_mon_Toan_Tieng_Anh_THPT___EVMD.Properties.Settings.Default.EVMDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbmlDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbmlDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbmlDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbmlDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Data> Datas
		{
			get
			{
				return this.GetTable<Data>();
			}
		}
		
		public System.Data.Linq.Table<Grade> Grades
		{
			get
			{
				return this.GetTable<Grade>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data")]
	public partial class Data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Word;
		
		private string _Meaning;
		
		private string _Usage;
		
		private string _Example;
		
		private System.Nullable<int> _MaGrade;
		
		private System.Nullable<bool> _Lop10;
		
		private System.Nullable<bool> _Lop11;
		
		private System.Nullable<bool> _Lop12;
		
		private EntityRef<Grade> _Grade;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWordChanging(string value);
    partial void OnWordChanged();
    partial void OnMeaningChanging(string value);
    partial void OnMeaningChanged();
    partial void OnUsageChanging(string value);
    partial void OnUsageChanged();
    partial void OnExampleChanging(string value);
    partial void OnExampleChanged();
    partial void OnMaGradeChanging(System.Nullable<int> value);
    partial void OnMaGradeChanged();
    partial void OnLop10Changing(System.Nullable<bool> value);
    partial void OnLop10Changed();
    partial void OnLop11Changing(System.Nullable<bool> value);
    partial void OnLop11Changed();
    partial void OnLop12Changing(System.Nullable<bool> value);
    partial void OnLop12Changed();
    #endregion
		
		public Data()
		{
			this._Grade = default(EntityRef<Grade>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Word", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Word
		{
			get
			{
				return this._Word;
			}
			set
			{
				if ((this._Word != value))
				{
					this.OnWordChanging(value);
					this.SendPropertyChanging();
					this._Word = value;
					this.SendPropertyChanged("Word");
					this.OnWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meaning", DbType="NVarChar(MAX)")]
		public string Meaning
		{
			get
			{
				return this._Meaning;
			}
			set
			{
				if ((this._Meaning != value))
				{
					this.OnMeaningChanging(value);
					this.SendPropertyChanging();
					this._Meaning = value;
					this.SendPropertyChanged("Meaning");
					this.OnMeaningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage", DbType="NVarChar(MAX)")]
		public string Usage
		{
			get
			{
				return this._Usage;
			}
			set
			{
				if ((this._Usage != value))
				{
					this.OnUsageChanging(value);
					this.SendPropertyChanging();
					this._Usage = value;
					this.SendPropertyChanged("Usage");
					this.OnUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Example", DbType="NVarChar(MAX)")]
		public string Example
		{
			get
			{
				return this._Example;
			}
			set
			{
				if ((this._Example != value))
				{
					this.OnExampleChanging(value);
					this.SendPropertyChanging();
					this._Example = value;
					this.SendPropertyChanged("Example");
					this.OnExampleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGrade", DbType="Int")]
		public System.Nullable<int> MaGrade
		{
			get
			{
				return this._MaGrade;
			}
			set
			{
				if ((this._MaGrade != value))
				{
					if (this._Grade.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGradeChanging(value);
					this.SendPropertyChanging();
					this._MaGrade = value;
					this.SendPropertyChanged("MaGrade");
					this.OnMaGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop10", DbType="Bit")]
		public System.Nullable<bool> Lop10
		{
			get
			{
				return this._Lop10;
			}
			set
			{
				if ((this._Lop10 != value))
				{
					this.OnLop10Changing(value);
					this.SendPropertyChanging();
					this._Lop10 = value;
					this.SendPropertyChanged("Lop10");
					this.OnLop10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop11", DbType="Bit")]
		public System.Nullable<bool> Lop11
		{
			get
			{
				return this._Lop11;
			}
			set
			{
				if ((this._Lop11 != value))
				{
					this.OnLop11Changing(value);
					this.SendPropertyChanging();
					this._Lop11 = value;
					this.SendPropertyChanged("Lop11");
					this.OnLop11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop12", DbType="Bit")]
		public System.Nullable<bool> Lop12
		{
			get
			{
				return this._Lop12;
			}
			set
			{
				if ((this._Lop12 != value))
				{
					this.OnLop12Changing(value);
					this.SendPropertyChanging();
					this._Lop12 = value;
					this.SendPropertyChanged("Lop12");
					this.OnLop12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grade_Data", Storage="_Grade", ThisKey="MaGrade", OtherKey="MaGrade", IsForeignKey=true)]
		public Grade Grade
		{
			get
			{
				return this._Grade.Entity;
			}
			set
			{
				Grade previousValue = this._Grade.Entity;
				if (((previousValue != value) 
							|| (this._Grade.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grade.Entity = null;
						previousValue.Datas.Remove(this);
					}
					this._Grade.Entity = value;
					if ((value != null))
					{
						value.Datas.Add(this);
						this._MaGrade = value.MaGrade;
					}
					else
					{
						this._MaGrade = default(Nullable<int>);
					}
					this.SendPropertyChanged("Grade");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grade")]
	public partial class Grade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GradeInt;
		
		private int _MaGrade;
		
		private EntitySet<Data> _Datas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGradeIntChanging(string value);
    partial void OnGradeIntChanged();
    partial void OnMaGradeChanging(int value);
    partial void OnMaGradeChanged();
    #endregion
		
		public Grade()
		{
			this._Datas = new EntitySet<Data>(new Action<Data>(this.attach_Datas), new Action<Data>(this.detach_Datas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeInt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GradeInt
		{
			get
			{
				return this._GradeInt;
			}
			set
			{
				if ((this._GradeInt != value))
				{
					this.OnGradeIntChanging(value);
					this.SendPropertyChanging();
					this._GradeInt = value;
					this.SendPropertyChanged("GradeInt");
					this.OnGradeIntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGrade", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGrade
		{
			get
			{
				return this._MaGrade;
			}
			set
			{
				if ((this._MaGrade != value))
				{
					this.OnMaGradeChanging(value);
					this.SendPropertyChanging();
					this._MaGrade = value;
					this.SendPropertyChanged("MaGrade");
					this.OnMaGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grade_Data", Storage="_Datas", ThisKey="MaGrade", OtherKey="MaGrade")]
		public EntitySet<Data> Datas
		{
			get
			{
				return this._Datas;
			}
			set
			{
				this._Datas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Datas(Data entity)
		{
			this.SendPropertyChanging();
			entity.Grade = this;
		}
		
		private void detach_Datas(Data entity)
		{
			this.SendPropertyChanging();
			entity.Grade = null;
		}
	}
}
#pragma warning restore 1591
